In [1]:
from numpy import *

In [2]:
data = array([[1,2,3],[1,2,3]])
print(data)

[[1 2 3]
 [1 2 3]]


In [3]:
data.shape

(2, 3)

In [4]:
zeros_matrix = zeros((1,2))
print(zeros_matrix)

[[0. 0.]]


In [5]:
ones_matrix = ones((1,2))
print(ones_matrix)

[[1. 1.]]


In [6]:
rand_matrix = random.randint(10, size = (10,5))
print(rand_matrix)

[[9 1 4 0 0]
 [8 7 8 5 7]
 [2 7 6 2 6]
 [0 3 7 9 6]
 [3 4 0 9 8]
 [7 2 0 2 4]
 [0 2 8 9 5]
 [2 4 5 6 2]
 [9 4 1 5 8]
 [9 9 1 5 8]]


In [11]:
col_vector = random.randint(10, size = (10,1))
print(col_vector)

[[5]
 [7]
 [2]
 [0]
 [4]
 [4]
 [1]
 [2]
 [0]
 [4]]


In [8]:
col_vector[0]

array([3])

In [9]:
print(col_vector[0])

[3]


In [10]:
col_vector = 100
print(col_vector)

100


In [12]:
col_vector[0] = 100
print(col_vector)

[[100]
 [  7]
 [  2]
 [  0]
 [  4]
 [  4]
 [  1]
 [  2]
 [  0]
 [  4]]


In [13]:
print(rand_matrix[0, 0])

9


In [14]:
print(rand_matrix[:,0:1])

[[9]
 [8]
 [2]
 [0]
 [3]
 [7]
 [0]
 [2]
 [9]
 [9]]


In [15]:
print(rand_matrix[0:1,:])

[[9 1 4 0 0]]


In [16]:
cols = array([1,2,3])
print(rand_matrix[0,cols])

[1 4 0]


In [17]:
flattened = rand_matrix.flatten()
print(flattened)

[9 1 4 0 0 8 7 8 5 7 2 7 6 2 6 0 3 7 9 6 3 4 0 9 8 7 2 0 2 4 0 2 8 9 5 2 4
 5 6 2 9 4 1 5 8 9 9 1 5 8]


In [19]:
rand_matrix_2 = random.randint(10, size = (5,2))
dot_product = rand_matrix.dot(rand_matrix_2)
print(dot_product)

[[ 71  94]
 [139 148]
 [ 81  86]
 [ 87  64]
 [ 91  66]
 [ 66  72]
 [ 84  62]
 [ 79  72]
 [110 110]
 [135 140]]
