In [1]:
from numpy import *

num_movies = 10
num_users = 5

ratings = random.randint(11, size = (num_movies, num_users))

print(ratings)

[[10 10  4  6 10]
 [ 6  4  0  4  6]
 [ 9  7 10 10 10]
 [10  9  4  6  6]
 [ 9 10  0  4  9]
 [ 4  3  8  9 10]
 [ 0  4  1  4 10]
 [10  3  4  7  4]
 [ 3  4  6 10  4]
 [ 3 10  3  3  2]]


In [2]:
did_rate = (ratings != 0) * 1
print(did_rate)

[[1 1 1 1 1]
 [1 1 0 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 0 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [3]:
jeevan_ratings = zeros((num_movies, 1))
print(jeevan_ratings)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [4]:
jeevan_ratings[0] = 8
jeevan_ratings[4] = 7
jeevan_ratings[7] = 3

print(jeevan_ratings)

[[8.]
 [0.]
 [0.]
 [0.]
 [7.]
 [0.]
 [0.]
 [3.]
 [0.]
 [0.]]


In [5]:
ratings = append(jeevan_ratings, ratings, axis = 1)
did_rate = append(((jeevan_ratings != 0) * 1), did_rate, axis = 1)

print(ratings)
print(did_rate)

[[ 8. 10. 10.  4.  6. 10.]
 [ 0.  6.  4.  0.  4.  6.]
 [ 0.  9.  7. 10. 10. 10.]
 [ 0. 10.  9.  4.  6.  6.]
 [ 7.  9. 10.  0.  4.  9.]
 [ 0.  4.  3.  8.  9. 10.]
 [ 0.  0.  4.  1.  4. 10.]
 [ 3. 10.  3.  4.  7.  4.]
 [ 0.  3.  4.  6. 10.  4.]
 [ 0.  3. 10.  3.  3.  2.]]
[[1 1 1 1 1 1]
 [0 1 1 0 1 1]
 [0 1 1 1 1 1]
 [0 1 1 1 1 1]
 [1 1 1 0 1 1]
 [0 1 1 1 1 1]
 [0 0 1 1 1 1]
 [1 1 1 1 1 1]
 [0 1 1 1 1 1]
 [0 1 1 1 1 1]]


In [6]:
# a function that normalizes a dataset

def normalize_ratings(ratings, did_rate):
    num_movies = ratings.shape[0]
    
    ratings_mean = zeros(shape = (num_movies, 1))
    ratings_norm = zeros(shape = ratings.shape)
    
    for i in range(num_movies):
        # Get all the indeses where there is a 1
        idx = where(did_rate[i] == 1)[0]
        # Calculate mean ratings of movie only from user's that gave a rating
        ratings_mean[i] = mean(ratings[i, idx])
        ratings_norm[i, idx] = ratings[i, idx] - ratings_mean[i]
        
    return (ratings_norm, ratings_mean)

In [7]:
ratings_norm, ratings_mean = normalize_ratings(ratings, did_rate)

In [8]:
print(ratings_norm)

[[ 0.          2.          2.         -4.         -2.          2.        ]
 [ 0.          1.         -1.          0.         -1.          1.        ]
 [ 0.         -0.2        -2.2         0.8         0.8         0.8       ]
 [ 0.          3.          2.         -3.         -1.         -1.        ]
 [-0.8         1.2         2.2         0.         -3.8         1.2       ]
 [ 0.         -2.8        -3.8         1.2         2.2         3.2       ]
 [ 0.          0.         -0.75       -3.75       -0.75        5.25      ]
 [-2.16666667  4.83333333 -2.16666667 -1.16666667  1.83333333 -1.16666667]
 [ 0.         -2.4        -1.4         0.6         4.6        -1.4       ]
 [ 0.         -1.2         5.8        -1.2        -1.2        -2.2       ]]


In [10]:
print(ratings_mean)

[[8.        ]
 [5.        ]
 [9.2       ]
 [7.        ]
 [7.8       ]
 [6.8       ]
 [4.75      ]
 [5.16666667]
 [5.4       ]
 [4.2       ]]


In [11]:
num_users = ratings.shape[1]
num_features = 3

In [12]:
movie_features = random.randn(num_movies, num_features)
user_prefs = random.randn(num_users, num_features)
initial_X_and_theta = r_[movie_features.T.flatten(), user_prefs.T.flatten()]
print(movie_features)

[[-1.43296138  1.10480706 -0.61857841]
 [-1.12135277 -0.46960736 -0.14956798]
 [ 0.91333947 -1.97632665 -0.03043332]
 [-1.37470566 -2.72753809 -0.75859618]
 [-1.11104493 -1.1613222  -0.71796845]
 [-0.43238861  1.45393957 -0.41304238]
 [ 2.87406588  0.366733   -0.22861924]
 [-0.40575603 -0.66731535 -0.65865018]
 [-2.33945729 -1.02865822 -0.98453902]
 [ 0.12794041 -0.08472257  1.47687763]]


In [13]:
print(user_prefs)

[[-0.15277818 -0.74636934  0.02816374]
 [-0.1643571   1.22481009  0.22491685]
 [ 0.13315699  0.18560661  0.78372242]
 [ 0.23157639  1.11804062  1.15300629]
 [-2.25664314  0.49157762  0.83758168]
 [ 0.01372869  0.81568704 -1.46502977]]


In [14]:
print(initial_X_and_theta)

[-1.43296138 -1.12135277  0.91333947 -1.37470566 -1.11104493 -0.43238861
  2.87406588 -0.40575603 -2.33945729  0.12794041  1.10480706 -0.46960736
 -1.97632665 -2.72753809 -1.1613222   1.45393957  0.366733   -0.66731535
 -1.02865822 -0.08472257 -0.61857841 -0.14956798 -0.03043332 -0.75859618
 -0.71796845 -0.41304238 -0.22861924 -0.65865018 -0.98453902  1.47687763
 -0.15277818 -0.1643571   0.13315699  0.23157639 -2.25664314  0.01372869
 -0.74636934  1.22481009  0.18560661  1.11804062  0.49157762  0.81568704
  0.02816374  0.22491685  0.78372242  1.15300629  0.83758168 -1.46502977]


In [15]:
initial_X_and_theta.shape

(48,)

In [16]:
def unroll_params(X_and_theta, num_users, num_movies, num_features):
    # Retrieve the X and theta matrixes from X_and_theta, based on their dimensions (num_features, num_movies, num_movies)
    # --------------------------------------------------------------------------------------------------------------
    # Get the first 30 (10 * 3) rows in the 48 X 1 column vector
    first_30 = X_and_theta[:num_movies * num_features]
    # Reshape this column vector into a 10 X 3 matrix
    X = first_30.reshape((num_features, num_movies)).transpose()
    # Get the rest of the 18 the numbers, after the first 30
    last_18 = X_and_theta[num_movies * num_features:]
    # Reshape this column vector into a 6 X 3 matrix
    theta = last_18.reshape(num_features, num_users ).transpose()
    return X, theta

In [17]:
def calculate_gradient(X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param):
    X, theta = unroll_params(X_and_theta, num_users, num_movies, num_features)
    
    # we multiply by did_rate because we only want to consider observations for which a rating was given
    difference = X.dot( theta.T ) * did_rate - ratings
    X_grad = difference.dot( theta ) + reg_param * X
    theta_grad = difference.T.dot( X ) + reg_param * theta
    
    # wrap the gradients back into a column vector 
    return r_[X_grad.T.flatten(), theta_grad.T.flatten()]

In [18]:
def calculate_cost(X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param):
    X, theta = unroll_params(X_and_theta, num_users, num_movies, num_features)
    
    # we multiply (element-wise) by did_rate because we only want to consider observations for which a rating was given
    cost = sum( (X.dot( theta.T ) * did_rate - ratings) ** 2 ) / 2
    # '**' means an element-wise power
    regularization = (reg_param / 2) * (sum( theta**2 ) + sum(X**2))
    return cost + regularization

In [19]:
from scipy import optimize
reg_param = 30

minimized_cost_and_optimal_params = optimize.fmin_cg(calculate_cost, fprime=calculate_gradient, x0=initial_X_and_theta, \
                                                     args=(ratings, did_rate, num_users, num_movies, num_features, reg_param), \
                                                     maxiter=100, disp=True, full_output=True)

Optimization terminated successfully.
         Current function value: 1104.263519
         Iterations: 15
         Function evaluations: 31
         Gradient evaluations: 31


In [20]:
cost, optimal_movie_features_and_user_prefs = minimized_cost_and_optimal_params[1], minimized_cost_and_optimal_params[0]

In [21]:
movie_features, user_prefs = unroll_params(optimal_movie_features_and_user_prefs, num_users, num_movies, num_features)

In [22]:
print(movie_features)

[[-1.610194   -0.30497468 -0.47652736]
 [-0.80930345 -0.15328404 -0.23950852]
 [-1.65518425 -0.31349572 -0.48984199]
 [-1.30178033 -0.24656017 -0.38525414]
 [-1.38754046 -0.26280333 -0.41063434]
 [-1.22045309 -0.23115688 -0.36118588]
 [-0.80068167 -0.15165095 -0.23695697]
 [-1.06557114 -0.2018218  -0.31534928]
 [-0.95229731 -0.18036734 -0.28182684]
 [-0.75987744 -0.14392257 -0.22488157]]


In [23]:
print(user_prefs)

[[-0.70949294 -0.13437975 -0.20997012]
 [-1.80652762 -0.34216048 -0.53463087]
 [-1.69055921 -0.32019569 -0.50031123]
 [-1.18015772 -0.22352465 -0.34926072]
 [-1.65313953 -0.31310849 -0.48923683]
 [-1.89921024 -0.35971481 -0.56205988]]


In [24]:
all_predictions = movie_features.dot( user_prefs.T )

In [25]:
print(all_predictions)

[[1.28346021 3.26797646 3.05819186 2.13488453 2.99050024 3.43563775]
 [0.64508299 1.64252543 1.53708509 1.07301939 1.50306245 1.72679407]
 [1.3193212  3.35928656 3.1436404  2.19453505 3.07405741 3.53163245]
 [1.03762851 2.64203403 2.47243121 1.72597252 2.41770512 2.77758178]
 [1.10598655 2.81608888 2.63531277 1.83967805 2.57698137 2.96056639]
 [0.9728039  2.47697608 2.31796899 1.61814443 2.26666185 2.60405564]
 [0.63821069 1.62502702 1.52070998 1.06158814 1.48704979 1.70839792]
 [0.84934989 2.16263459 2.02380635 1.41279326 1.97901036 2.27358708]
 [0.75906116 1.93273931 1.80866897 1.26260862 1.76863494 2.03189717]
 [0.60568637 1.54221282 1.44321196 1.00748776 1.41126715 1.621335  ]]


In [26]:
predictions_for_jeevan = all_predictions[:, 0:1] + ratings_mean

In [27]:
print(predictions_for_jeevan)

[[ 9.28346021]
 [ 5.64508299]
 [10.5193212 ]
 [ 8.03762851]
 [ 8.90598655]
 [ 7.7728039 ]
 [ 5.38821069]
 [ 6.01601656]
 [ 6.15906116]
 [ 4.80568637]]


In [28]:
print(jeevan_ratings)

[[8.]
 [0.]
 [0.]
 [0.]
 [7.]
 [0.]
 [0.]
 [3.]
 [0.]
 [0.]]
