In [1]:
import pandas as pd
import numpy as np

In [2]:
header = ['user_id', 'item_id', 'rating', 'timestamp']
dataset = pd.read_csv('data/ratings_Digital_Music.csv', names=header)

In [3]:
dataset.head()

user_id     item_id  rating   timestamp
0  A2EFCYXHNK06IS  5555991584     5.0   978480000
1  A1WR23ER5HMAA9  5555991584     5.0   953424000
2  A2IR4Q0GPAFJKW  5555991584     4.0  1393545600
3  A2V0KUVAB9HSYO  5555991584     4.0   966124800
4  A1J0GL9HCA7ELW  5555991584     5.0  1007683200

In [4]:
df = dataset.head(10000)

In [5]:
n_users = df.user_id.unique().shape[0]
n_items = df.item_id.unique().shape[0]
print ('Number of users = ' , str(n_users) , ' | Number of movies = ' , str(n_items))

Number of users =  8355  | Number of movies =  500


In [6]:
from sklearn import cross_validation as cv
train_data, test_data = cv.train_test_split(df, test_size=0.25)

/home/mauli/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [7]:
train_data.head()

user_id     item_id  rating   timestamp
5644   A3Q4XAQXKKV6V  B000000OB7     4.0  1253923200
3389  A1YW6VUR42BN13  B00000064G     5.0   960076800
7096  A12PR0EVHU108V  B000000OWM     5.0  1073433600
960   A31RZMVAFMLB8B  B00000017R     5.0  1360800000
6150   ANH213Y0DZZIV  B000000OQS     5.0  1382745600

In [8]:
test_data.head()

user_id     item_id  rating   timestamp
3085   ACVTSUHK6WNGQ  B00000064F     5.0  1078790400
5090  A3KNENJHFW7JCL  B000000I0H     5.0  1179273600
3578   A4MBICSNR9ZP0  B0000009OU     5.0  1176249600
4497  A1S2H5GMIGP3IR  B000000EYE     5.0  1356652800
7720  A3R08XQ3E95JGR  B000000VC2     5.0  1061510400

In [9]:
train_data_matrix = train_data.pivot(index='user_id', columns='item_id', values='rating').fillna(0)
train_data_matrix.head()

item_id                5555991584  6308051551  7901622466  B0000000ZW  \
user_id                                                                 
A04345582HHNXEA9SAET4         0.0         0.0         0.0         0.0   
A07465992K7FVSL53VA9B         0.0         0.0         0.0         0.0   
A08161909WK3HU7UYTMW          0.0         0.0         0.0         0.0   
A086594320Z777EHOFWKU         0.0         0.0         0.0         0.0   
A10175AMUHOQC4                0.0         0.0         0.0         0.0   

item_id                B00000016T  B00000016W  B00000017R  B0000001BA  \
user_id                                                                 
A04345582HHNXEA9SAET4         0.0         0.0         0.0         0.0   
A07465992K7FVSL53VA9B         0.0         0.0         0.0         0.0   
A08161909WK3HU7UYTMW          0.0         0.0         0.0         0.0   
A086594320Z777EHOFWKU         0.0         0.0         0.0         0.0   
A10175AMUHOQC4                0.0         0.0         0.0         0.0   

item_id                B0000001BO  B0000001O0     ...      B0000011CU  \
user_id                                           ...                   
A04345582HHNXEA9SAET4         0.0         0.0     ...             0.0   
A07465992K7FVSL53VA9B         0.0         0.0     ...             0.0   
A08161909WK3HU7UYTMW          0.0         0.0     ...             0.0   
A086594320Z777EHOFWKU         0.0         0.0     ...             0.0   
A10175AMUHOQC4                0.0         0.0     ...             0.0   

item_id                B0000011GU  B0000011MD  B0000011N5  B0000011P7  \
user_id                                                                 
A04345582HHNXEA9SAET4         0.0         0.0         0.0         0.0   
A07465992K7FVSL53VA9B         0.0         0.0         0.0         0.0   
A08161909WK3HU7UYTMW          0.0         0.0         0.0         0.0   
A086594320Z777EHOFWKU         0.0         0.0         0.0         0.0   
A10175AMUHOQC4                0.0         0.0         0.0         0.0   

item_id                B0000011WE  B0000011X5  B0000011XM  B00000127G  \
user_id                                                                 
A04345582HHNXEA9SAET4         0.0         0.0         0.0         0.0   
A07465992K7FVSL53VA9B         0.0         0.0         0.0         0.0   
A08161909WK3HU7UYTMW          0.0         0.0         0.0         0.0   
A086594320Z777EHOFWKU         0.0         0.0         0.0         0.0   
A10175AMUHOQC4                0.0         0.0         0.0         0.0   

item_id                B0000012T3  
user_id                            
A04345582HHNXEA9SAET4         0.0  
A07465992K7FVSL53VA9B         0.0  
A08161909WK3HU7UYTMW          0.0  
A086594320Z777EHOFWKU         0.0  
A10175AMUHOQC4                0.0  

[5 rows x 488 columns]

In [10]:
train_data_matrix.shape

(6433, 488)

In [11]:
test_data_matrix = test_data.pivot(index='user_id', columns='item_id', values='rating').fillna(0)
test_data_matrix.head()

item_id         5555991584  6308051551  7901622466  B0000000ZW  B00000016T  \
user_id                                                                      
A102VKCQOZD2C          0.0         0.0         0.0         0.0         0.0   
A102X8CNVNLINY         0.0         0.0         0.0         0.0         0.0   
A104ID0XLCHNGH         0.0         0.0         0.0         0.0         0.0   
A104VHIMHTA3V9         0.0         0.0         0.0         0.0         0.0   
A105S56ODHGJEK         0.0         0.0         0.0         0.0         0.0   

item_id         B00000016W  B00000017R  B0000001BA  B0000001BO  B0000001PS  \
user_id                                                                      
A102VKCQOZD2C          0.0         0.0         0.0         0.0         0.0   
A102X8CNVNLINY         0.0         0.0         0.0         0.0         0.0   
A104ID0XLCHNGH         0.0         0.0         0.0         0.0         0.0   
A104VHIMHTA3V9         0.0         0.0         0.0         0.0         0.0   
A105S56ODHGJEK         0.0         0.0         0.0         0.0         0.0   

item_id            ...      B0000011C1  B0000011CU  B0000011GU  B0000011MD  \
user_id            ...                                                       
A102VKCQOZD2C      ...             0.0         0.0         0.0         0.0   
A102X8CNVNLINY     ...             0.0         0.0         0.0         0.0   
A104ID0XLCHNGH     ...             0.0         0.0         0.0         0.0   
A104VHIMHTA3V9     ...             0.0         0.0         0.0         0.0   
A105S56ODHGJEK     ...             0.0         0.0         0.0         0.0   

item_id         B0000011N5  B0000011P7  B0000011WE  B0000011XM  B00000127G  \
user_id                                                                      
A102VKCQOZD2C          0.0         0.0         0.0         0.0         0.0   
A102X8CNVNLINY         0.0         0.0         0.0         0.0         0.0   
A104ID0XLCHNGH         0.0         0.0         0.0         0.0         0.0   
A104VHIMHTA3V9         0.0         0.0         0.0         0.0         0.0   
A105S56ODHGJEK         0.0         0.0         0.0         0.0         0.0   

item_id         B0000012T3  
user_id                     
A102VKCQOZD2C          0.0  
A102X8CNVNLINY         0.0  
A104ID0XLCHNGH         0.0  
A104VHIMHTA3V9         0.0  
A105S56ODHGJEK         0.0  

[5 rows x 405 columns]

In [12]:
test_data_matrix.shape

(2316, 405)

In [13]:
from sklearn.metrics.pairwise import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix, metric='cosine')
item_similarity = pairwise_distances(train_data_matrix.T, metric='cosine')

In [14]:
user_similarity

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

In [15]:
item_similarity

array([[0.        , 1.        , 1.        , ..., 0.99221753, 1.        ,
        1.        ],
       [1.        , 0.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 0.        , ..., 1.        , 1.        ,
        1.        ],
       ...,
       [0.99221753, 1.        , 1.        , ..., 0.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 0.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        0.        ]])

In [16]:
def predict(ratings, similarity, type='user'):
    if type == 'user':
        mean_user_rating = ratings.mean(axis=1)
        #You use np.newaxis so that mean_user_rating has same format as ratings
        #ratings_diff = (ratings - mean_user_rating[:, np.newaxis])
        ratings_diff = ratings.sub(ratings.mean(axis=1), axis=0)
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred = ratings.dot(similarity).div(pd.DataFrame(np.array([np.abs(similarity).sum(axis=1)])).iloc[0]).values
    return pred

In [17]:
item_prediction = predict(train_data_matrix, item_similarity, type='item')
user_prediction = predict(train_data_matrix, user_similarity, type='user')

In [18]:
item_prediction

array([[0.00205451, 0.00205339, 0.00205351, ..., 0.00205613, 0.00205339,
        0.00205951],
       [0.00821806, 0.00821355, 0.00821406, ..., 0.00822454, 0.00821355,
        0.00823804],
       [0.01027257, 0.01026694, 0.01026757, ..., 0.01028067, 0.01026694,
        0.00958645],
       ...,
       [0.01027257, 0.01026694, 0.01026757, ..., 0.01028067, 0.01026694,
        0.01029755],
       [0.00821806, 0.00821355, 0.00821406, ..., 0.00810915, 0.00821355,
        0.00823804],
       [0.01027257, 0.01026694, 0.01026757, ..., 0.01028067, 0.01026694,
        0.01029755]])

In [19]:
from sklearn.metrics import mean_squared_error
from math import sqrt
def rmse(prediction, ground_truth):
    prediction = prediction[ground_truth.nonzero()].flatten()
    ground_truth = ground_truth[ground_truth.nonzero()].flatten()
    return sqrt(mean_squared_error(prediction, ground_truth))

In [20]:
print ('User-based CF RMSE: ' , str(rmse(user_prediction, test_data_matrix.values)))
print ('Item-based CF RMSE: ' , str(rmse(item_prediction, test_data_matrix.values)))

User-based CF RMSE:  4.602509446146999
Item-based CF RMSE:  4.621668673446618


In [21]:
sparsity=round(1.0-len(df)/float(n_users*n_items),3)
print ('The sparsity level of Music dataset 10000 is ' ,  str(sparsity*100) , '%')

The sparsity level of Music dataset 10000 is  99.8 %


In [23]:
import scipy.sparse as sp
from scipy.sparse.linalg import svds

#get SVD components from train matrix. Choose k.
u, s, vt = svds(train_data_matrix, k = 20)
s_diag_matrix=np.diag(s)
X_pred = np.dot(np.dot(u, s_diag_matrix), vt)
print ('User-based CF MSE: ' , str(rmse(X_pred, test_data_matrix.values)))

User-based CF MSE:  4.62429367759624
